app:
  token:
    expirationTime: 500000
    refreshTime: 1000000
    secret: fe60f199041040557dc61317117ad37f10d2352cc8f3ccc32abb11056f6a864b
  venv: /home/phat/Documents/Open-Course

redis:
  host: localhost
  port: 6379

frontend:
  url: http://localhost:5173

kafka:
  boostrap-server: 127.0.0.1:9091,127.0.0.1:9092,127.0.0.1:9093
  group-id: open-course
  topic:
    notification: notification-topic
    course: cdb.course.course
    category: cdb.course.category
    section: cdb.course.section
    content: cdb.course.content

logging:
  level:
    org:
      apache:
        kafka: DEBUG
      springframework:
        kafka: INFO

payment:
  vnpay:
    tmn-code: EV13SRGJ
    init-payment-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    return-url: http://localhost:5173/checkout/callback
    timeout: 15
    secret-key: 54VR6BH2L1QJLWTNLIQYK4U4ZAU2U63O

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    oauth2:
      client:
        registration:
          google:
            prefix-uri: https://accounts.google.com/o/oauth2/auth
            client-id: ${OAUTH_CLIENT_ID}
            client-secret: ${OAUTH_CLIENT_SECRET}
            redirect-uri: http://localhost:5173/auth/login/callback
            scope: >
              https://www.googleapis.com/auth/userinfo.profile
              https://www.googleapis.com/auth/userinfo.email
              https://www.googleapis.com/auth/user.phonenumbers.read
        registration:
          google:
            user-info-uri: https://people.googleapis.com/v1/people/me?personFields=emailAddresses,names,phoneNumbers,photos
