version: "3.0"
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/root/redis
  redis-insight:
    image: redis/redisinsight
    ports:
      - 5540:5540
volumes:
  redis-data: